"""HEIC support (CONTRACT-heic H1-H9, core patch K1). Every HEIC here is generated by tests/_heicgen.py."""
import io
import os
import unittest

import numpy as np

import _heicgen
import _iccgen
import _util
from darkroom import read_image

# Tolerances, verbatim from CONTRACT-heic H4.
SRGB8_MAX, SRGB8_MEAN = 2 / 255, 0.5 / 255
SRGB10_MAX, SRGB10_MEAN = 0.004, 0.001
P3_10_LIN_MAX, P3_10_LIN_MEAN = 0.003, 0.0005    # Display P3 against the expected sRGB, in linear light
P3_8_LIN_MAX, P3_8_LIN_MEAN = 0.008, 0.0015


def srgb_icc():
    from PIL import ImageCms
    return ImageCms.ImageCmsProfile(ImageCms.createProfile("sRGB")).tobytes()


def lin_diff(a, b):
    return diff(_heicgen.srgb_decode(a), _heicgen.srgb_decode(b))


def diff(a, b):
    d = np.abs(np.asarray(a, np.float64) - np.asarray(b, np.float64))
    return float(d.max()), float(d.mean())


class HeicCase(unittest.TestCase):
    def setUp(self):
        self.d = _util.tmpdir(self)

    def p(self, name):
        return os.path.join(self.d, name)


class TestReadFormats(HeicCase):  # H1
    def test_extensions_any_case(self):
        img = _heicgen.pattern(32, 48)
        for name in ("a.heic", "b.HEIC", "c.heif", "d.HeIf"):
            out = read_image(_heicgen.write_heic(self.p(name), img))
            self.assertEqual(out.shape, (32, 48, 3))
            self.assertEqual(out.dtype, np.float32)
            self.assertGreaterEqual(float(out.min()), 0.0)
            self.assertLessEqual(float(out.max()), 1.0)

    def test_unicode_path_and_read_only(self):
        path = _heicgen.write_heic(self.p("照片 一.heic"), _heicgen.pattern(16, 16))
        before = (os.path.getsize(path), os.path.getmtime(path))
        read_image(path)
        self.assertEqual((os.path.getsize(path), os.path.getmtime(path)), before)

    def test_primary_only_with_thumbnail_and_second_image(self):
        img = _heicgen.pattern(40, 60)
        other = np.zeros((20, 30, 3))
        path = _heicgen.write_heic(self.p("multi.heic"), img, thumbnail=True, second_image=other)
        out = read_image(path)
        self.assertEqual(out.shape, (40, 60, 3))
        self.assertLessEqual(diff(out, img)[0], SRGB8_MAX + 0.5 / 255)


class TestDepthAndColour(HeicCase):  # H2, H3, H4
    def test_srgb_8bit_matches_png(self):
        img = _heicgen.pattern()
        heic = read_image(_heicgen.write_heic(self.p("s8.heic"), img, bits=8, icc=srgb_icc()))
        png = read_image(_heicgen.write_png8(self.p("s8.png"), img))
        mx, mean = diff(heic, png)
        self.assertLessEqual(mx, SRGB8_MAX, mx)
        self.assertLessEqual(mean, SRGB8_MEAN, mean)

    def test_no_profile_is_srgb(self):
        img = _heicgen.pattern()
        heic = read_image(_heicgen.write_heic(self.p("n8.heic"), img, bits=8))
        png = read_image(_heicgen.write_png8(self.p("n8.png"), img))
        self.assertLessEqual(diff(heic, png)[0], SRGB8_MAX)

    def test_srgb_10bit_matches_png16(self):
        img = _heicgen.pattern()
        heic = read_image(_heicgen.write_heic(self.p("s10.heic"), img, bits=10, icc=srgb_icc()))
        png = read_image(_heicgen.write_png16(self.p("s10.png"), img))
        mx, mean = diff(heic, png)
        self.assertLessEqual(mx, SRGB10_MAX, mx)
        self.assertLessEqual(mean, SRGB10_MEAN, mean)

    def test_10bit_not_reduced_to_8bit(self):
        img = _heicgen.ramp_10bit()
        out = read_image(_heicgen.write_heic(self.p("ramp.heic"), img, bits=10))
        self.assertGreaterEqual(len(np.unique(out[..., 0])), 1000)
        self.assertLessEqual(diff(out, img)[0], SRGB10_MAX)

    def test_p3_10bit_matches_reference(self):
        img = _heicgen.pattern()
        p3 = _heicgen.srgb_to_p3(img)
        self.assertGreater(diff(p3, img)[0], 0.03)        # P3 encoding really differs from sRGB
        out = read_image(_heicgen.write_heic(self.p("p3_10.heic"), p3, bits=10, icc=_iccgen.display_p3()))
        mx, mean = lin_diff(out, img)
        self.assertLessEqual(mx, P3_10_LIN_MAX, mx)
        self.assertLessEqual(mean, P3_10_LIN_MEAN, mean)
        wrong = read_image(_heicgen.write_heic(self.p("p3_as_srgb.heic"), p3, bits=10))   # profile ignored
        self.assertGreater(lin_diff(wrong, img)[0], 10 * P3_10_LIN_MAX)

    def test_p3_8bit_matches_reference(self):
        img = _heicgen.pattern()
        out = read_image(_heicgen.write_heic(self.p("p3_8.heic"), _heicgen.srgb_to_p3(img), bits=8,
                                             icc=_iccgen.display_p3()))
        mx, mean = lin_diff(out, img)
        self.assertLessEqual(mx, P3_8_LIN_MAX, mx)
        self.assertLessEqual(mean, P3_8_LIN_MEAN, mean)

    def test_p3_outside_srgb_is_clipped_not_broken(self):
        red = np.zeros((8, 8, 3))
        red[..., 0] = 1.0
        out = read_image(_heicgen.write_heic(self.p("p3red.heic"), red, bits=10, icc=_iccgen.display_p3()))
        self.assertTrue(np.isfinite(out).all())
        self.assertAlmostEqual(float(out[..., 0].min()), 1.0, places=3)
        self.assertLess(float(out[..., 1].max()), 0.01)

    def test_test_profile_agrees_with_littlecms(self):
        """The hand-built P3 profile is a valid ICC: LittleCMS converts it like the published matrices do."""
        from PIL import Image, ImageCms
        img = _heicgen.pattern(16, 16)
        src = Image.fromarray((_heicgen.srgb_to_p3(img) * 255 + 0.5).astype(np.uint8))
        prof = ImageCms.ImageCmsProfile(io.BytesIO(_iccgen.display_p3()))
        srgb = ImageCms.ImageCmsProfile(ImageCms.createProfile("sRGB"))
        out = np.asarray(ImageCms.profileToProfile(src, prof, srgb, outputMode="RGB")) / 255.0
        self.assertLessEqual(diff(out, img)[0], 3 / 255)

    def test_windows_srgb_profile_parses(self):
        """A real-world matrix/TRC profile with a 1024-entry curv table (read-only, outside the repo)."""
        from darkroom import _icc
        p = os.path.join(os.environ.get("WINDIR", "C:/Windows"), "System32", "spool", "drivers", "color",
                         "sRGB Color Space Profile.icm")
        if not os.path.exists(p):
            self.skipTest("Windows sRGB profile not present")
        with open(p, "rb") as f:
            data = f.read()
        conv = _icc.from_icc(data)
        self.assertIsNotNone(conv)
        img = _heicgen.pattern(16, 16).astype(np.float32)
        self.assertLessEqual(diff(conv(img), img)[0], 2e-3)


class TestOrientation(HeicCase):  # H5
    def test_orientation_applied_once(self):
        from PIL import Image
        img = _heicgen.pattern(48, 80)
        src8 = Image.fromarray((img * 255 + 0.5).astype(np.uint8))
        for tag, op in ((3, Image.Transpose.ROTATE_180), (6, Image.Transpose.ROTATE_270),
                        (8, Image.Transpose.ROTATE_90)):
            out = read_image(_heicgen.write_heic(self.p(f"o{tag}.heic"), img, orientation=tag))
            want = np.asarray(src8.transpose(op)) / 255.0
            self.assertEqual(out.shape, want.shape, tag)
            self.assertLessEqual(diff(out, want)[0], SRGB8_MAX, tag)


class TestBroken(HeicCase):  # H6
    def broken_files(self):
        good = _heicgen.write_heic(self.p("good.heic"), _heicgen.pattern(64, 64))
        with open(good, "rb") as f:
            data = f.read()
        out = {}
        for name, blob in (("trunc_head.heic", data[:40]), ("trunc_half.heic", data[: len(data) // 2]),
                           ("garbage.heic", os.urandom(4096)), ("empty.heif", b""),
                           ("jpeg_inside.heic", b"\xff\xd8\xff\xe0" + b"\0" * 100)):
            with open(self.p(name), "wb") as f:
                f.write(blob)
            out[name] = self.p(name)
        return out

    def test_broken_heic_raises_value_error(self):
        for name, path in self.broken_files().items():
            with self.assertRaises(ValueError, msg=name) as cm:
                read_image(path)
            self.assertTrue(str(cm.exception).startswith("HEIC 解碼失敗："), str(cm.exception))

    def test_damaged_but_decodable_data_does_not_crash(self):
        good = _heicgen.write_heic(self.p("good2.heic"), _heicgen.pattern(64, 64))
        with open(good, "rb") as f:
            data = f.read()
        for k, cut in enumerate((len(data) * 3 // 4, len(data) - 16)):
            path = self.p(f"zeroed{k}.heic")
            with open(path, "wb") as f:
                f.write(data[:cut] + b"\0" * (len(data) - cut))
            try:
                out = read_image(path)
            except ValueError as e:
                self.assertTrue(str(e).startswith("HEIC 解碼失敗："))
            else:
                self.assertEqual(out.shape, (64, 64, 3))
                self.assertTrue(np.isfinite(out).all())

    def test_broken_heic_cli_error_line(self):
        files = self.broken_files()
        preset = os.path.join(self.d, "p.xmp")
        import _xmpgen
        _xmpgen.write(self.d, "p.xmp", _xmpgen.xmp_text({"Exposure2012": "+0.5"}))
        out_path = self.p("out.png")
        rc, out, err = _util.run_cli("apply", "--preset", preset, files["trunc_half.heic"], out_path)
        self.assertEqual(rc, 2)
        lines = err.splitlines()
        self.assertEqual(len(lines), 1)
        self.assertTrue(lines[0].startswith(f"照片讀取失敗：{files['trunc_half.heic']}：HEIC 解碼失敗："), lines[0])
        self.assertFalse(os.path.exists(out_path))


class TestCli(HeicCase):  # H8
    def test_apply_reads_heic(self):
        import _xmpgen
        _xmpgen.write(self.d, "p.xmp", _xmpgen.xmp_text({"Exposure2012": "+0.5"}, name="亮"))
        src = _heicgen.write_heic(self.p("in.HEIC"), _heicgen.pattern(), bits=10, icc=_iccgen.display_p3())
        for out_name in ("o.png", "o.jpg", "o.tif"):
            rc, out, err = _util.run_cli("apply", "--preset", self.p("p.xmp"), src, self.p(out_name))
            self.assertEqual(rc, 0, err)
            self.assertEqual(out.splitlines(), [f"已套用：亮（強度 100%）→ {self.p(out_name)}"])
            self.assertEqual(read_image(self.p(out_name)).shape, (96, 128, 3))
        rc, out, err = _util.run_cli("apply", "--preset", self.p("p.xmp"), src, self.p("o.heic"))
        self.assertEqual(rc, 2)
        self.assertEqual(err.splitlines(),
                         ["不支援的輸出格式：.heic（可用 .png、.tif、.tiff 16-bit 或 .jpg 8-bit）"])


if __name__ == "__main__":
    unittest.main()
